# Constants

In [29]:
import tensorflow as tf
a = tf.constant([[1, 2], [3, 4], [5, 6]])
b = tf.constant(0, dtype=None, shape = (2,3), name = 'Const', verify_shape= False)
c = tf.zeros((4,5), dtype=tf.float32, name="c")
d = tf.zeros_like(c)
e = tf.fill((1,2), 9, name="e")

with tf.Session() as sess:
    print sess.run(a) 
    print sess.run(b) 
    print sess.run(c)  
    print sess.run(d) 
    print sess.run(e) 


[[1 2]
 [3 4]
 [5 6]]
[[0 0 0]
 [0 0 0]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[9 9]]


# Variables

In [59]:
import tensorflow as tf
w = tf.Variable(3, name="w")
twod= tf.Variable([1,2], name="twod")
threed = tf.Variable([[1,2],[3,7],[8,9]], name="threed")
four = tf.Variable(tf.zeros(1,1))
assign = four.assign([2])
add = four.assign_add([5])

init_op = tf.global_variables_initializer()

with tf.Session() as sessv:
    sessv.run(init_op)
    print sessv.run(w) 
    print sessv.run(twod) 
    print sessv.run(threed) 
    print("Before assign")
    print sessv.run(four)
    print sessv.run(assign)
    print("After Assign")
    print sessv.run(four)
    print("Before add")
    print sessv.run(add)
    print("After add")
    print sessv.run(four)

3
[1 2]
[[1 2]
 [3 7]
 [8 9]]
Before assign
[ 0.]
[ 2.]
After Assign
[ 2.]
Before add
[ 7.]
After add
[ 7.]


## Placeholders

In [74]:
##1
a = tf.placeholder(tf.float32, shape=[1])
b = tf.placeholder(tf.float32, shape=[1])
c = a+b
init_op = tf.global_variables_initializer()


##2
d = tf.placeholder(tf.float32, shape=[3])
e = tf.placeholder(tf.float32, shape=[3])
f = d*e

#3

x =[[1],[2],[3],[4],[5],[6],[7]]
l = tf.placeholder(tf.int32, shape=[1])
h = 4 * l


#4
n = tf.placeholder(tf.float32, shape=(5, 5))
y = tf.matmul(n, n)

#5
r = tf.placeholder(tf.float32, shape=None)
s = tf.placeholder(tf.float32, shape=None)
t = r/s


with tf.Session() as sess:
    sess.run(init_op)
    print("first.")

    print sess.run(c,{a:[1],b:[2]})
    print("two.")

    print sess.run(f,{d:[1,3,4],e:[2,5,6]})
    print("three.")
 
    for e in x:
        print sess.run(h,{l:e})
    print("four.")  
    print sess.run(y,{n:[[1,3,4,5,8],[1,3,4,5,8],[1,3,4,5,8],[1,3,4,5,8],[1,3,4,5,8]]})
    
    print("five.")
    print sess.run(t,{r:4,s:2})    

first.
[ 3.]
two.
[  2.  15.  24.]
three.
[4]
[8]
[12]
[16]
[20]
[24]
[28]
four.
[[  21.   63.   84.  105.  168.]
 [  21.   63.   84.  105.  168.]
 [  21.   63.   84.  105.  168.]
 [  21.   63.   84.  105.  168.]
 [  21.   63.   84.  105.  168.]]
five.
2.0


## Operations